language: scala

jdk:
  - oraclejdk8

scala:
   - 2.11.8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt
    - $HOME/.ivy2

before_install:
  - npm install source-map-support
  - phantomjs --version
  - npm install phantomjs-prebuilt
  - export PATH=$PWD/node_modules/phantomjs-prebuilt/lib/phantom/bin:$PATH
  - phantomjs --version

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage cron4sJVM/test

after_success:
  - sbt coverageReport && sbt coverageAggregate
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master